# Generated by Django 4.1.7 on 2023-02-27 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Animal',
            new_name='Todo',
        ),
    ]
